### ISSUE TITLE
Please provide a ready compiled file!

### ISSUE THREAD

**Issue by ted051** [EU1KY/eu1ky_aa_v3_h745#1]
Unfortunately the compiling did not work for me. My laptop needed about 4 hours, then I got the message "internal error". Would it be possible to publish a finished file? Then I could test.
Best regards
Wolfgang Kiefer (DH1AKF)****

**Comment by EU1KY** [comment]
Hi Wolfgang,
You are doing something wrong. Build takes ~30 second on Windows. Did you follow all instructions? On what stage it stucks?
The Travis CI is connected to GitHub, and it builds automatically every time I push the changes to the repo. See, for example, the results of the latest build https://travis-ci.com/EU1KY/eu1ky_aa_v3_h745/builds/151265070
Will send you the binary by email.
73!

**Comment by ted051** [comment]
Hi Yury,

many thanks for your quick response to my question, and for the .bin file. Now I have the firmware on my STM332H Disco board and can do some tests.

 

Today I have new installed the cygwin, GNU tools for ARM, Github Desktop...

But there are some errors in my installation:

 

ErrorMake.jpg

 

The pathes are set, I have no idea, how to fix the errors...

 

73, Wolfgang

 

 

 

Von: Yury K [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. März 2020 21:47
An: EU1KY/eu1ky_aa_v3_h745
Cc: Wolfgang Kiefer; Author
Betreff: Re: [EU1KY/eu1ky_aa_v3_h745] Please provide a ready compiled file! (#1)

 

Hi Wolfgang,
You are doing something wrong. Build takes ~30 second on Windows. Did you follow all instructions? On what stage it stucks?
The Travis CI is connected to GitHub, and it builds automatically every time I push the changes to the repo. See, for example, the results of the latest build https://travis-ci.com/EU1KY/eu1ky_aa_v3_h745/builds/151265070
Will send you the binary by email.
73!
